services:
  wfexternaleventpotentialissue:
    image: wfexternaleventpotentialissue
    pull_policy: never
    build:
      context: .
      dockerfile: WFExternalEventPotentialIssue/Dockerfile
    ports:
      - 65000:8080
    networks:
      - workflow-network

  wfexternaleventpotentialissue-dapr:
    image: "daprio/daprd:1.15.5"
    command: [ "./daprd",
               "-app-id", "wfexternaleventpotentialissue-app",
               "-app-port", "8080",
               "-placement-host-address", "placement:50005",
               "-scheduler-host-address", "scheduler-0:50006",
               "-resources-path", "/components",
               "-log-level","debug" ]
    volumes:
      - "./components/:/components"
    depends_on:
      scheduler-0:
        condition: service_started
      postgres-db:
        condition: service_healthy
    network_mode: "service:wfexternaleventpotentialissue"
    
  placement:
    image: "daprio/dapr:1.15.4"
    command: ["./placement",
              "-port", "50005",
              "-log-level","warn"]
    networks:
      - workflow-network
  
  scheduler-0:
    image: "daprio/dapr:1.15.4"
    command: ["./scheduler",
              "--etcd-data-dir", "/var/run/dapr/scheduler"
    ]
    volumes:
      - ./dapr_scheduler/0:/var/run/dapr/scheduler
    networks:
      - workflow-network

  postgres-db:
    image: postgres:16.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - max_wal_size=2GB
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    networks:
      - workflow-network
    volumes:
      - postgres-db-16-2:/var/lib/postgresql/data

networks:
  workflow-network:
    external: true

volumes:
  postgres-db-16-2:
    driver: local
  components-data: